name: 'Close a milestone by title'
description: 'Close a milestone with the given title'
branding:
  icon: 'check-square'
  color: 'gray-dark'
inputs:
  title:
    description: 'The title of the milestone'
    required: true
outputs:
  number:
    description: 'The number of the recently closed milestone'
runs:
  using: 'docker'
  image: 'Dockerfile'
